# Generated by Django 4.0.6 on 2022-07-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0002_studysession_end_time_topic_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(default='temp', max_length=20),
            preserve_default=False,
        ),
    ]
