# Generated by Django 4.0.6 on 2022-07-29 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0004_studysession_time_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
