# Generated by Django 4.0.6 on 2022-07-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0006_topic_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
    ]
